export type { TrellisClientConfig, EntityConfig, QueryConfig, PresenceConfig } from './types.js'

export { TrellisProvider } from './provider.js'
export { getTrellisClient } from './context.js'
export { TrellisEntity } from './entity.js'
export { TrellisEntityList } from './entity-list.js'
export { TrellisQuery } from './query.js'
export { resolveShell } from './shells.js'
export { TrellisShell } from './shell.js'
export { TrellisSidebar } from './sidebar.js'
export { TrellisSidebarNav } from './sidebar-nav.js'
export type { NavItem, NavZone } from './sidebar-nav.js'
export { TrellisHeader } from './header.js'
export { TrellisBreadcrumb } from './breadcrumb.js'
export type { BreadcrumbSegment } from './breadcrumb.js'
export { TrellisSearch } from './search.js'
export { TrellisViewToggle } from './view-toggle.js'
export type { ViewOption } from './view-toggle.js'
export { TrellixQuery } from './trellix-query.js'

export type { TrellisEditorExport } from './editor/trellis-editor.js'
export { TrellisEditor } from './editor/trellis-editor.js'

import './provider.js'
import './entity.js'
import './entity-list.js'
import './query.js'
import './shell.js'
import './sidebar.js'
import './sidebar-nav.js'
import './header.js'
import './breadcrumb.js'
import './search.js'
import './view-toggle.js'
import './trellix-query.js'
